### ISSUE TITLE
腾讯 Cloud Studio  flux nf4 安裝方式

### ISSUE THREAD

**Issue by love9678** [aigem/aitools#1]
使用Llama3.2 - RAG SFT 版模安裝  會有475GB
apt-get update -y && apt-get install curl -y
curl -sSf https://sshx.io/get | sh -s run
apt-get update -y
git clone https://openi.pcl.ac.cn/niubi/aitools.git
cd aitools
bash aitools.sh
cd workspace
python /workspace/ComfyUI/main.py
ngrok config add-authtoken
ngrok http http://localhost:8188

pip install aria2
模型下載:
cd /workspace/ComfyUI/models/checkpoints
aria2c -c -x 16 -s 16 -k 1M https://hf-mirror.com/lllyasviel/flux1-dev-bnb-nf4/resolve/main/flux1-dev-bnb-nf4-v2.safetensors -o flux1-dev-bnb-nf4-v2.safetensors
cd /workspace/ComfyUI/models/unet
aria2c -c -x 16 -s 16 -k 1M https://hf-mirror.com/city96/FLUX.1-dev-gguf/resolve/main/flux1-dev-Q6_K.gguf -o flux1-dev-Q6_K.gguf
comfyui节点安裝位置
cd /workspace/ComfyUI/models/checkpoints
git clone git clone https://gitclone.com/github.com/city96/ComfyUI-GGUF
git clone https://gitclone.com/github.com/comfyanonymous/ComfyUI
 
付上國內:github伐理下載方式  https://www.gitclone.com/
國內模型載地址:https://hf-mirror.com

**Comment by wocnorz** [comment]
非常详细，感谢。油管上你也评论过我的视频？

**Comment by aigem** [comment]
非常详细，感谢。油管上你也评论我的视频？
